version: '3.7'
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 821252
      POSTGRES_USER: docker
    container_name: postgresDB
    ports:

      - "5432:5432"
    volumes:
      - ./var/lib/postgresql/data
      - ./createdb.sh:/docker-entrypoint-initdb.d/create_CREATE SEQUENCE hibernate_sequence START 1;createdb.sh


  weathermonitoring:
    image: weather
    build: ./
    ports:
      - "8082:8082"
    depends_on:
      - database

volumes:
  apps-volumes:

# Теперь мы можем запустить Postgres с помощью одной простой команды: $ docker-compose up
# или запустите Postgres в фоновом режиме: $ docker-compose up -d
# И остановите службу Postgres: $ docker-compose down

#  В этом случае мы сопоставили наш локальный порт 5438 с портом 5432 (порт по умолчанию Postgres)
#  внутри контейнера., Также мы будем сохранять данные на нашей машине, предотвращая потерю данных
#  при удалении контейнеров, для этого мы добавляем том, используя папка postgres-data как место,
#  где хранятся данные Postgres.

#  Чтобы создать таблицы в нашей базе данных, нам нужно скопировать наш init.sql скрипт
#  в/docker-entrypoint-initdb.d/

# Официальный образ PostgreSQL Docker https://hub.docker.com/_/postgres/ позволяет нам размещать
#  файлы SQL в /docker-entrypoint-initdb.d/ папке, и при первом запуске службы она импортирует
#  и выполнит эти файлы SQL.