server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 821252
    username: docker
    url: jdbc:postgresql://database:5432/dockerdb

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update


token:
  name: ?api_token=1AH2IEr7GiWSiuxS

data:
  name: /202112180100